version: "3.7"

services:
  jekyll_site:
    image: jekyll/jekyll:4.0
    command: ["jekyll", "serve", "--watch", "--draft"]
    ports:
      - "4000:4000"
    volumes:
     - type: bind
       source: .
       target: /srv/jekyll